% driver to generate the iDN1 model generation results in "Mechanistic
% model-driven exometabolomic characterization of human dopaminergic
% neuronal metabolism"
%
% Note: The results are saved in the directory specified by each driver,
% currently the main results are saved in:
% '~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1'

%% XomicsToModel data preparation

% Recon 3D
% Preparation of the generic Recon3D model with thermodynamic data,
% information on formed and broken bonds, and addition of names in some
% reactions. It excludes the expression of the reactions because that is
% specific information which it is included in XomicsToModel.
%
% The generic model is saved in :
% '~/work/sbgCloud/programExperimental/projects/xomics/data/Recon3D_301/Recon3DModel_301_xomics_input.mat'

driver_prepareRecon3Model

% Specific data preprocessing
% The tables transcriptomicsData and exoMet, which are used in the variable
% specificData, are generated using the function transcriptomics2genes and
% the script conc2Fluxes.

% The external files are saved in:
% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/data/xomics

driver_specificDataPreprocessing

%% iDN1 model generation

% Generate iDopaNeuro model conditions with different conditions using the
% function XomicsToMultipleModels. The current conditions are
%
%   1. Generic model: Recon3DModel_301_xomics_input
%   2. cobraSolver: gurobi
%   3. tissueSpecificSolver: fastCore - thermoKernel
%   4. activeGenesApproach: deleteModelGenes - oneRxnPerActiveGene
%   5. transcriptomicThreshold: [0 2]
%   6. limitBounds: [1e3 1e4]
%   7. inactiveGenesTranscriptomics: [true false]
%   8. closeIons: [true false]
%   9. curationOverOmics: [true false]
%
% The models are saved in:
% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1

driver_createMultipleIDNModels

% The predictive capacity of each model generated by driver_createMultipleIDNModels
% is evaluated using the modelPredictiveCapacity function to ifentify the
% model with the highest score. The features to consider are the flux consistency
% of reactions and metabolites, the predictive capacity of uptakes and secretions,
% the Euclidean distance to the experimental values, the number of metabolites,
% and the number of reactions. Save the results as accuracy.mat in each directory
%
% The models are saved in:
% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1

driver_testiDNmodelPredictiveCapacity

% Identify the most accurate model based on the results of driver_testiDNmodelPredictiveCapacity.m.
% The information gathered from each model is used to identify two sets of conditions:
%   - The conditions for the model with the highest score;
%   - The conditions with the highest score on each condition used.
%
% The models are saved in:
% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1

driver_identifyMostAccurateiDNModel

%% Statistics 

driver_vennMetabolites
driver_actinveInactiveGenesRxns

%% Perturbation analysis

% driver_perturbationAnalysis

%% Sparse FBA
% The driver generates a graph comparing the fraction of reactions in and 
% out of the minimal flux vector in each metabolic subsystem of the 
% iDopaNeuro1 model.
 
driver_sparseFBA

%% Uncertainty reduction
% Uniform sampling of feasible solution space, was used to predict a set of 
% metabolites that could potentially be secreted by the iDN model. 
% In principle, all of these metabolites should be considered for targeted 
% metabolomic analyses in exometabolomic experiments.

driver_uncertaintyReduction
 

